# Generated by Django 3.0.7 on 2020-09-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200929_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impuesto',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Porcentaje'),
        ),
    ]
