# Generated by Django 3.0.7 on 2020-10-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200929_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenmantenimiento',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('EN_REVISION', 'En revisión'), ('REVISADO', 'Revisado'), ('FINALIZADO', 'Finalizado')], default='NUEVO', max_length=50, verbose_name='Estado'),
        ),
    ]
