# Generated by Django 3.0.7 on 2020-10-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201018_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisiontecnica',
            name='fecha_revision',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de revisión'),
        ),
    ]
