# Generated by Django 3.0.7 on 2020-10-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20201018_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenmantenimiento',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('EN_REVISION', 'En revisión'), ('REVISADO', 'Revisado'), ('CONFIRMADO', 'Confirmado'), ('FINALIZADO', 'Finalizado')], default='NUEVO', max_length=50, verbose_name='Estado'),
        ),
    ]
