# Generated by Django 3.0.7 on 2020-10-22 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20201022_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='store.Producto'),
        ),
    ]
