# Generated by Django 3.0.7 on 2020-10-23 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20201022_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='fechaVenta',
            new_name='fecha_venta',
        ),
    ]
