# Generated by Django 3.0.7 on 2020-10-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20201023_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Impuesto'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='precioUnitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total'),
        ),
    ]
