# Generated by Django 3.0.7 on 2020-10-23 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20201023_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total'),
        ),
        migrations.CreateModel(
            name='PagoFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de compra')),
                ('mmonto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Precio Unitario')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='store.Factura')),
            ],
        ),
    ]
