# Generated by Django 3.0.7 on 2020-10-23 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20201023_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallecompra',
            old_name='precioUnitario',
            new_name='precio_unitario',
        ),
        migrations.RenameField(
            model_name='detallefactura',
            old_name='precioUnitario',
            new_name='precio_unitario',
        ),
    ]
