# Generated by Django 3.0.7 on 2020-10-23 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20201023_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagofactura',
            old_name='mmonto',
            new_name='monto',
        ),
    ]
