# Generated by Django 3.0.7 on 2020-10-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20201024_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='descripcion',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='mision',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='vision',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Dirección'),
        ),
    ]
