# Generated by Django 3.0.7 on 2020-12-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20201027_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='products/images'),
        ),
    ]
