# Generated by Django 3.0.7 on 2020-12-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_producto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleorden',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('EN_REVISION', 'En revisión'), ('REVISADO', 'Revisado'), ('CONFIRMADO', 'Confirmado'), ('ARREGLADO', 'Arreglado'), ('FINALIZADO', 'Finalizado')], default='NUEVO', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='gallery/products'),
        ),
    ]
