# Generated by Django 3.0.7 on 2020-10-20 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20201004_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='is_admin',
            new_name='is_active',
        ),
    ]
