# Generated by Django 3.0.7 on 2020-10-22 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20201020_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='people.Persona'),
        ),
    ]
